CREATE TABLE IF NOT EXISTS `Users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`avatar` VARCHAR(255) NOT NULL,
    `pass` VARCHAR(255) NOT NULL,
    `lang` VARCHAR(255) NOT NULL,
    `about` VARCHAR(255) NULL DEFAULT NULL,
	`created` INT(11) NULL DEFAULT NULL,
	`edited` INT(11) NULL DEFAULT NULL,
	`logged` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;